version: "2"
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - goconst
    - gocyclo
    - revive
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - wrapcheck
    - staticcheck
    - unused
  settings:
    wrapcheck:
      ignore-package-globs:
      - github.com/labstack/echo/v4 # Ignore all methods in echo package
    revive:
      rules:
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/blurfx/fxoj

