-- +goose Up
-- +goose StatementBegin
CREATE TABLE "problem_testcases" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "problem_id" bigint,
  "draft_id" bigint,
  "input_attachment_id" bigint NOT NULL,
  "output_attachment_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id"),
  CONSTRAINT "problem_testcases_problems" FOREIGN KEY ("problem_id") REFERENCES "problems" ("id"),
  CONSTRAINT "problem_testcases_problem_drafts" FOREIGN KEY ("draft_id") REFERENCES "problem_drafts" ("id")
);

CREATE TABLE "problem_sample_testcases" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "problem_id" bigint,
  "draft_id" bigint,
  "input" text NOT NULL,
  "output" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id"),
  CONSTRAINT "problem_sample_testcases_problems" FOREIGN KEY ("problem_id") REFERENCES "problems" ("id"),
  CONSTRAINT "problem_sample_testcases_problem_drafts" FOREIGN KEY ("draft_id") REFERENCES "problem_drafts" ("id")
);
-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP TABLE "problem_testcases";

DROP TABLE "problem_sample_testcases";
-- +goose StatementEnd

