-- +goose Up
-- create "problems" table
CREATE TABLE
    "problems" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "title" text NOT NULL,
        "description" text NOT NULL,
        "spoiler" text NOT NULL,
        "time_limit" bigint NOT NULL,
        "memory_limit" bigint NOT NULL,
        "draft_mapping_id" bigint,
        "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "deleted_at" timestamptz,
        PRIMARY KEY ("id")
    );

CREATE TABLE
    "problem_drafts" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "title" text NOT NULL,
        "description" text NOT NULL,
        "spoiler" text NOT NULL,
        "time_limit" bigint NOT NULL,
        "memory_limit" bigint NOT NULL,
        "draft_mapping_id" bigint,
        "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "deleted_at" timestamptz,
        PRIMARY KEY ("id")
    );

CREATE TABLE
    "problem_draft_mappings" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "problem_id" bigint NOT NULL,
        "draft_id" bigint NOT NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "problem_draft_mappings_problems" FOREIGN KEY ("problem_id") REFERENCES "problems" ("id"),
        CONSTRAINT "problem_draft_mappings_problem_drafts" FOREIGN KEY ("draft_id") REFERENCES "problem_drafts" ("id")
    );

CREATE TABLE
    "problem_testcases" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "problem_id" bigint NOT NULL,
        "draft_id" bigint NOT NULL,
        "input_attachment_id" bigint NOT NULL,
        "output_attachment_id" bigint NOT NULL,
        "example" boolean NOT NULL DEFAULT FALSE,
        "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "deleted_at" timestamptz,
        PRIMARY KEY ("id"),
        CONSTRAINT "problem_testcases_problems" FOREIGN KEY ("problem_id") REFERENCES "problems" ("id"),
        CONSTRAINT "problem_testcases_problem_drafts" FOREIGN KEY ("draft_id") REFERENCES "problem_drafts" ("id")
    );

-- create user_role enum
CREATE TYPE "user_role" AS ENUM ('admin', 'author', 'user');

-- create "users" table
CREATE TABLE
    "users" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "username" varchar(255) NOT NULL,
        "password" varchar(512) NOT NULL,
        "role" user_role NOT NULL DEFAULT 'user',
        "last_login_at" timestamptz,
        "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "deleted_at" timestamptz,
        PRIMARY KEY ("id")
    );

-- create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");

-- create "problem_authors" table
CREATE TABLE
    "problem_authors" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "problem_id" bigint NOT NULL,
        "user_id" bigint NOT NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "problem_authors_problems_authors" FOREIGN KEY ("problem_id") REFERENCES "problems" ("id"),
        CONSTRAINT "problem_authors_users_authored_problems" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
    );

-- create index "problemauthor_problem_id" to table: "problem_authors"
CREATE INDEX "problemauthor_problem_id" ON "problem_authors" ("problem_id");

-- create index "problemauthor_user_id" to table: "problem_authors"
CREATE INDEX "problemauthor_user_id" ON "problem_authors" ("user_id");

-- create "problem_contributors" table
CREATE TYPE "problem_contributor_type" AS ENUM ('reviewer');

CREATE TABLE
    "problem_contributors" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "type" problem_contributor_type NOT NULL,
        "problem_id" bigint NOT NULL,
        "user_id" bigint NOT NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "problem_contributors_problems_contributors" FOREIGN KEY ("problem_id") REFERENCES "problems" ("id"),
        CONSTRAINT "problem_contributors_users_contributed_problems" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
    );

-- create "languages" table
CREATE TABLE
    "languages" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "name" varchar(255) NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "deleted_at" timestamptz,
        PRIMARY KEY ("id")
    );

-- create "submissions" table
CREATE TYPE "submission_status" AS ENUM (
    'pending',
    'running',
    'accepted',
    'wrong_answer',
    'time_limit_exceeded',
    'memory_limit_exceeded',
    'runtime_error',
    'compile_error',
    'system_error'
);

CREATE TYPE "submission_visibility" AS ENUM ('public', 'private', 'solved_only');

CREATE TABLE
    "submissions" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "code" text NOT NULL,
        "time_limit" bigint NOT NULL,
        "memory_limit" bigint NOT NULL,
        "status" character varying NOT NULL,
        "visibility" submission_visibility NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "deleted_at" timestamptz,
        "language_id" bigint NOT NULL,
        "problem_id" bigint NOT NULL,
        "user_id" bigint NOT NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "submissions_languages_submissions" FOREIGN KEY ("language_id") REFERENCES "languages" ("id"),
        CONSTRAINT "submissions_problems_submissions" FOREIGN KEY ("problem_id") REFERENCES "problems" ("id"),
        CONSTRAINT "submissions_users_submissions" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
    );

-- create index "submission_language_id" to table: "submissions"
CREATE INDEX "submission_language_id" ON "submissions" ("language_id");

-- create index "submission_problem_id" to table: "submissions"
CREATE INDEX "submission_problem_id" ON "submissions" ("problem_id");

-- create index "submission_status" to table: "submissions"
CREATE INDEX "submission_status" ON "submissions" ("status");

-- create index "submission_user_id" to table: "submissions"
CREATE INDEX "submission_user_id" ON "submissions" ("user_id");

-- +goose Down
-- reverse: create index "submission_user_id" to table: "submissions"
DROP INDEX "submission_user_id";

-- reverse: create index "submission_status" to table: "submissions"
DROP INDEX "submission_status";

-- reverse: create index "submission_problem_id" to table: "submissions"
DROP INDEX "submission_problem_id";

-- reverse: create index "submission_language_id" to table: "submissions"
DROP INDEX "submission_language_id";

-- reverse: create "submissions" table
DROP TABLE "submissions";

-- reverse: create "languages" table
DROP TABLE "languages";

-- reverse: create "problem_contributors" table
DROP TABLE "problem_contributors";

-- reverse: create index "problemauthor_user_id" to table: "problem_authors"
DROP INDEX "problemauthor_user_id";

-- reverse: create index "problemauthor_problem_id" to table: "problem_authors"
DROP INDEX "problemauthor_problem_id";

-- reverse: create "problem_authors" table
DROP TABLE "problem_authors";

-- reverse: create index "users_username_key" to table: "users"
DROP INDEX "users_username_key";

-- reverse: create "users" table
DROP TABLE "users";

-- reverse: create "problem_draft_mappings" table
DROP TABLE "problem_draft_mappings";

-- reverse: create "problem_drafts" table
DROP TABLE "problem_drafts";

-- reverse: create "problems" table
DROP TABLE "problems";

DROP TYPE "user_role";

DROP TYPE "submission_visibility";

DROP TYPE "submission_status";

DROP TYPE "problem_contributor_type";