version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=oj-root-pass
      - MYSQL_DATABASE=onlinejudge
    volumes:
      - './.localdb:/var/lib/mysql'
    ports:
      - 3306:3306
