version: '3'

services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=judge_admin
      - POSTGRES_PASSWORD=judge_pass
    volumes:
      - './.localdb:/var/lib/postgres'
    ports:
      - 5432:5432
